[tool.poetry]
name = "projeto"
version = "0.1.0"
description = ""
authors = ["Lucas Alves <lucas.alves@beemon.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
