# Generated by Django 5.2.1 on 2025-05-23 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.CharField(max_length=50, verbose_name="marca")),
                ("model", models.CharField(max_length=50, verbose_name="modelo")),
                (
                    "kind",
                    models.CharField(
                        choices=[("analog", "Analogico"), ("digital", "Digital")],
                        max_length=50,
                        verbose_name="tipo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "serial_number",
                    models.CharField(max_length=50, verbose_name="número de série"),
                ),
                (
                    "tag_number",
                    models.CharField(max_length=50, verbose_name="número de tag"),
                ),
                ("bought_at", models.DateTimeField(verbose_name="comprado em")),
                ("location", models.CharField(max_length=50, verbose_name="local")),
                (
                    "maintenance_periodicity",
                    models.DurationField(verbose_name="periodicidade de manutenção"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventiva"),
                            ("corrective", "Corretiva"),
                            ("calibration", "Calibração"),
                            ("qualification", "Qualificação"),
                            ("check", "Checagem"),
                        ],
                        max_length=50,
                        verbose_name="tipo",
                    ),
                ),
                ("send_at", models.DateTimeField(verbose_name="enviado em")),
                ("returned_at", models.DateTimeField(verbose_name="retornado em")),
                ("due_at", models.DateTimeField(verbose_name="vence em")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="preço"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=50, verbose_name="certificado de calibração"
                    ),
                ),
                (
                    "certificate_results",
                    models.TextField(verbose_name="faixas e pontos de calibração"),
                ),
                ("observation", models.TextField(verbose_name="observação")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
