# Generated by Django 5.2.1 on 2025-06-23 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.CharField(max_length=50, verbose_name="marca")),
                ("model", models.CharField(max_length=50, verbose_name="modelo")),
                (
                    "kind",
                    models.CharField(
                        choices=[("analog", "Analogico"), ("digital", "Digital")],
                        max_length=50,
                        verbose_name="tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Itens",
            },
        ),
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nome"),
                ),
            ],
            options={
                "verbose_name": "Laboratório",
                "verbose_name_plural": "Laboratórios",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "serial_number",
                    models.CharField(max_length=50, verbose_name="número de série"),
                ),
                (
                    "tag_number",
                    models.CharField(max_length=50, verbose_name="número de tag"),
                ),
                ("bought_at", models.DateTimeField(verbose_name="comprado em")),
                (
                    "maintenance_periodicity",
                    models.IntegerField(verbose_name="periodicidade de manutenção"),
                ),
                (
                    "calibration_periodicity",
                    models.IntegerField(verbose_name="periodicidade de calibração"),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="arquivado"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment.asset",
                        verbose_name="equipamento",
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment.laboratory",
                        verbose_name="laboratório",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preventive_maintenance", "Manutenção Preventiva"),
                            ("corrective_maintenance", "Manutenção Corretiva"),
                            ("calibration", "Calibração"),
                            ("qualification", "Qualificação"),
                            ("check", "Checagem"),
                        ],
                        max_length=50,
                        verbose_name="tipo",
                    ),
                ),
                ("send_at", models.DateTimeField(verbose_name="enviado em")),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="retornado em"
                    ),
                ),
                ("due_at", models.DateTimeField(verbose_name="vence em")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="preço"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=50, verbose_name="certificado de calibração"
                    ),
                ),
                (
                    "certificate_results",
                    models.TextField(verbose_name="faixas e pontos de calibração"),
                ),
                ("observation", models.TextField(verbose_name="observação")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment.equipment",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
    ]
