# Generated by Django 5.2.1 on 2025-06-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "Equipment", "verbose_name_plural": "Equipment"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AlterModelOptions(
            name="laboratory",
            options={
                "verbose_name": "Laboratory",
                "verbose_name_plural": "Laboratories",
            },
        ),
        migrations.AlterField(
            model_name="asset",
            name="brand",
            field=models.CharField(max_length=50, verbose_name="brand"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="kind",
            field=models.CharField(
                choices=[("analog", "Analog"), ("digital", "Digital")],
                max_length=50,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="model",
            field=models.CharField(max_length=50, verbose_name="model"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="archived"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.asset",
                verbose_name="equipment",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="bought_at",
            field=models.DateTimeField(verbose_name="bought at"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="calibration_periodicity",
            field=models.IntegerField(verbose_name="calibration periodicity"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="laboratory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.laboratory",
                verbose_name="laboratory",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="maintenance_periodicity",
            field=models.IntegerField(verbose_name="maintenance periodicity"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(max_length=50, verbose_name="serial number"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="tag_number",
            field=models.CharField(max_length=50, verbose_name="tag number"),
        ),
        migrations.AlterField(
            model_name="event",
            name="certificate_number",
            field=models.CharField(
                max_length=50, verbose_name="calibration certificate"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="certificate_results",
            field=models.TextField(verbose_name="calibration ranges and points"),
        ),
        migrations.AlterField(
            model_name="event",
            name="due_at",
            field=models.DateTimeField(verbose_name="due at"),
        ),
        migrations.AlterField(
            model_name="event",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="equipment.equipment",
                verbose_name="item",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="kind",
            field=models.CharField(
                choices=[
                    ("preventive_maintenance", "Preventive Maintenance"),
                    ("corrective_maintenance", "Corrective Maintenance"),
                    ("calibration", "Calibration"),
                    ("qualification", "Qualification"),
                    ("check", "Check"),
                ],
                max_length=50,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="observation",
            field=models.TextField(verbose_name="observation"),
        ),
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="returned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="returned at"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="send_at",
            field=models.DateTimeField(verbose_name="sent at"),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
    ]
