# Generated by Django 5.2.1 on 2025-05-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_maintenance_returned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="maintenance_periodicity",
            field=models.IntegerField(verbose_name="periodicidade de manutenção"),
        ),
    ]
