# Generated by Django 5.2.1 on 2025-06-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_asset_options_alter_equipment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringEquipment",
            fields=[],
            options={
                "verbose_name": "Expiring Equipment",
                "verbose_name_plural": "Expiring Equipment",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("equipment.equipment",),
        ),
    ]
