# Generated by Django 5.2.1 on 2025-06-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_alter_item_maintenance_periodicity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Item", "verbose_name_plural": "Itens"},
        ),
        migrations.AlterModelOptions(
            name="maintenance",
            options={
                "verbose_name": "Manutenção",
                "verbose_name_plural": "Manutenções",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="arquivado"),
        ),
    ]
