# Generated by Django 5.2.1 on 2025-06-12 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0004_alter_asset_options_alter_item_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.asset",
                verbose_name="equipamento",
            ),
            preserve_default=False,
        ),
    ]
