# Generated by Django 5.2.1 on 2025-07-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_asset_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "Equipment", "verbose_name_plural": "Equipments"},
        ),
        migrations.RemoveField(
            model_name="event",
            name="due_at",
        ),
        migrations.AddField(
            model_name="equipment",
            name="calibration_due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="calibration due date"
            ),
        ),
    ]
