# Generated by Django 5.2.1 on 2025-06-12 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_item_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="calibration_periodicity",
            field=models.IntegerField(
                default=365, verbose_name="periodicidade de calibração"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preventive_maintenance", "Manutenção Preventiva"),
                            ("corrective_maintenance", "Manutenção Corretiva"),
                            ("calibration", "Calibração"),
                            ("qualification", "Qualificação"),
                            ("check", "Checagem"),
                        ],
                        max_length=50,
                        verbose_name="tipo",
                    ),
                ),
                ("send_at", models.DateTimeField(verbose_name="enviado em")),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="retornado em"
                    ),
                ),
                ("due_at", models.DateTimeField(verbose_name="vence em")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="preço"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=50, verbose_name="certificado de calibração"
                    ),
                ),
                (
                    "certificate_results",
                    models.TextField(verbose_name="faixas e pontos de calibração"),
                ),
                ("observation", models.TextField(verbose_name="observação")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.DeleteModel(
            name="Maintenance",
        ),
    ]
