# Generated by Django 5.2.1 on 2025-07-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0006_alter_equipment_options_remove_event_due_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExpiringEquipment",
        ),
        migrations.AddField(
            model_name="event",
            name="requires_recalibration",
            field=models.BooleanField(
                default=False, verbose_name="requires recalibration"
            ),
        ),
    ]
