# Generated by Django 5.2.1 on 2025-06-23 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="laboratory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.laboratory",
                verbose_name="laboratório",
            ),
        ),
    ]
