# Generated by Django 5.2.1 on 2025-06-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_laboratory"),
        ("equipment", "0002_alter_asset_options_alter_equipment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="laboratory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="equipment.laboratory",
                verbose_name="laboratory",
            ),
        ),
    ]
